### ISSUE TITLE
Lerasium spike causes crash

### ISSUE THREAD

**Issue by DiceOf20** [leafreynolds/cosmere#115]
### Issue description

I am using the port version and I tried to put a lerasium spike in (the one with all the powers) and it crashed me. I can no longer boot the world
Caused by: java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / minecraft:damage_type]: ResourceKey[minecraft:damage_type / cosmere:spiked]

### Steps to reproduce

Put lerasium spike in
Profit

### Minecraft version

1.19.2 (Latest)

### Forge version

47.3.0

### Cosmere version

port branch

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/LjObzVB

**Comment by leafreynolds** [comment]
this will be related to me not committing the full datagen changes, runData gets rid of the old copy of spike damage types

for now, just don't use spikes, sorry. Lerasium/lerasatium nuggets will work
