### ISSUE TITLE
Coinpouch behaving oddly

### ISSUE THREAD

**Issue by R0b0r0b** [leafreynolds/cosmere#126]
### Issue description

When you open the coin pouch, the name is rendered as "translation.coinpouch.allomancy" and appears in blocky black font.

Also, if you put nuggets in the pouch, then move it to a different inventory slot, some or all of the nuggets will have been deleted. The game also no longer allows copper nuggets, I assume due to them being recognised as vanilla nuggets. The same problem applies with iron and gold nuggets.

### Steps to reproduce

1. Open the pouch. Note the blocky black font and the "translation.coinpouch.allomancy".
2. Try and fail to put copper nuggets in the pouch. (The same happens with iron and gold)
3. Place a few cadmium nuggets in the pouch, close it to get some more from the Creative inventory. When you open it again, the nuggets will be missing.

### Minecraft version

1.20.1 (Latest)

### Forge version

47.3.0

### Cosmere version

Cosmere-1.20.1-47.3.0-0.7.95

**Comment by Gerbagel** [comment]
Oddly, the only bugs I'm experiencing are copper not wanting to go in, and the broken translation string. All other nuggets go in and stay in. They also deplete correctly. Are you sure about nuggets disappearing?

**Comment by R0b0r0b** [comment]
I am sure - though I've had this issue on 1.19 versions as well, so it might just be to do with lag

**Comment by leafreynolds** [comment]
Unfortunately the coin pouch losing items occasionally is an old bug that I haven't solved. We will need to reimplement them better.

**Comment by Gerbagel** [comment]
Fixed with 76b0adc23e29fba8dbed1c9ec6833a9656396589 and 80977cec7d05bedf5af6dbfa7a7b34263fa804c2
