### ISSUE TITLE
Ironpulling and Steelpushing on Items or Mobs

### ISSUE THREAD

**Issue by CapoReader5395** [leafreynolds/cosmere#127]
### Issue description

Sometimes when you try to pull or push a metallic Item you get pulled or pushed to that item and not the Item to you. The same is with some Mobs holding metallic Items, for example Zombified Piglins 

### Steps to reproduce

1. Start by creating a World and get a-iron or a-steel 
2. Try to push or pull an metallic Item or a Mob with an metallic Item 

### Minecraft version

1.20.1 (Latest)

### Forge version

47.3.0

### Cosmere version

Cosmere-1.20.1-47.3.0-0.7.95

**Comment by Gerbagel** [comment]
Should be fixed with 2687af48417b4d73bd788600f4c7e2152bbef0f3
