### ISSUE TITLE
Copper tools dont work

### ISSUE THREAD

**Issue by Wildfin45** [leafreynolds/cosmere#128]
### Issue description

In the Cosmere: tools and armor mod, specifically the copper tools are incapable of mining blocks they are intended to, and only those blocks.

### Steps to reproduce

1. Download cosmere suite
2. Make a copper axe, pickaxe, or shovel
3. Try to mine the matching block for those items

### Minecraft version

1.20.1 (Latest)

### Forge version

47.3.0

### Cosmere version

Cosmere-1.20.1-47.3.0-0.7.95.jar

### Other relevant versions

As far as I am aware it's only on the singular currently existing version for 1.20.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

No crash log as it doesn't crash

**Comment by leafreynolds** [comment]
![image](https://github.com/user-attachments/assets/38f357a5-e602-4647-b546-06af973c1e26)

@Gerbagel

**Comment by Gerbagel** [comment]
I've done nothing wrong :)

(I'll fix)

**Comment by Gerbagel** [comment]
Done
