### ISSUE TITLE
Infinite Stormlight glitch, Peculiarities with Progression, and Gravitation Grievances

### ISSUE THREAD

**Issue by R0b0r0b** [leafreynolds/cosmere#132]
### Issue description

So, two problems.
One is that, when I breathe in Stormlight from gems, the amount of Stormlight remaining in the gem does not change - this happens regardless of whether I'm in Creative or Survival. (And I am definitely able to breathe it in - I get the jump boost, speed, and haste effects)

The other issue is that, provided I have the Surge of Progression, I can produce the green "Villager XP" sparkles by right-clicking with an empty hand, regardless of whether I actually have Stormlight in my system or not. Though I can't heal or grow plants unless I have Stormlight, so that seems to be working as intended.
(Relatedly, Lashing enemies is still a little bit strange...if I punch an enemy while using Gravitation, they fly up so far and so fast that they basically despawn outright, unless there's blocks above them.)

### Steps to reproduce

-Infinite Stormlight
1. Either use commands to give yourself a Surge or grab an Honorblade from Creative menu
2. Get a gemstone of your preferred type from the Creative menu, crouch and right-click to inhale the Stormlight
3. Marvel at the fact that you have not depleted the gem's Stormlight reserves

-Progression Peculiarities
1. Grant yourself Progression, either through commands or an Honorblade
2. Right-click on a block or mob with an empty hand, watch the pretty green sparkles. (Unrelatedly, when I first discovered this, I was frantically right-clicking a spawned-in Cryptic to heal it after I accidentally hurt it. Thought I was bonding it at first, and got very excited, until I later realised that it's just a problem with Progression.)

-Gravitation Grievances
1. Grant yourself Gravitation, either through commands or an Honorblade
2. Left-click on a mob, watch as it flies off so fast that it just disappears altogether.  

### Minecraft version

1.20.1 (Latest)

### Forge version

47.3.0

### Cosmere version

Cosmere-1.20.1-47.3.0-0.7.95

**Comment by leafreynolds** [comment]
Gravitation grievances, that's actually a sort-of-joke feature. Referencing book 2 where Szeth was launching people into the sky. I should probably turn it into a real power, rather than something someone can accidentally do.

**Comment by leafreynolds** [comment]
Progression, that's supposed to be showing you that you're healing a mob. Feedback on power activated.

**Comment by leafreynolds** [comment]
Hopefully fixed in next version, excepting the gravitation thing. I also couldn't get the particles to show up on blocks when they shouldn't. That might actually be the feature for trying to progress from coarse dirt to dirt, or dirt to grass etc.
