### ISSUE TITLE
Gold Spikes with feruchemical electrum gives both feruchemical electrum and feruchemical atium.

### ISSUE THREAD

**Issue by AngelOfCreation** [leafreynolds/cosmere#32]
### Issue description

Title. Think it might have to do with leaf.cosmere.feruchemy.common.manifestation.FeruchemyAtium at the following line:
`@Override
	public Attribute getAttribute()
	{
		return FeruchemyAttributes.FERUCHEMY_ATTRIBUTES.get(Metals.MetalType.ELECTRUM).getAttribute();
	}`

### Steps to reproduce

Grab a feruchemical electrum gold spike from creative.
Slot it in.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.3

### Cosmere version

Build 58

**Comment by leafreynolds** [comment]
Working as intended.

[See this WoB explanation for why all atium mistings were actually electrum mistings](https://wob.coppermind.net/events/456/#e15110)
