### ISSUE TITLE
Metal triggering other metals effects?

### ISSUE THREAD

**Issue by MoonlitJolteon** [leafreynolds/cosmere#47]
"I noticed earlier that I got the brightness effect from A-Tin while burning bronze, and my friend is getting the F-Tin zoom while tapping steel"

![](https://media.discordapp.net/attachments/1176036505798590484/1176036506448695316/image.png?ex=656d6858&is=655af358&hm=7d90685aa9576eb98a3cc1acdaca98082a708569bdedad34b7e2376dcc280115&=&width=1266&height=701)

**Comment by Gerbagel** [comment]
I think this should be set to done. We figured out that it wasn't a bug with the Cosmere suite, but rather another mod (still unsure which) that reverses the speed FoV change
