### ISSUE TITLE
[Allomancy] Metal Vial eating things it shouldn't

### ISSUE THREAD

**Issue by Giltsmith** [leafreynolds/cosmere#54]
### Issue description

When filling a metal vial with nuggets, if you place other blocks or items into the crafting grid it will consume them as well.

### Steps to reproduce

Put metal vial into crafting grid with metal nugget (i.e tin)
Place other block into crafting grid
Craft the vial

### Minecraft version

1.19.2 (Latest)

### Forge version

43.3.5

### Cosmere version

build 77

**Comment by leafreynolds** [comment]
![image](https://github.com/user-attachments/assets/acb334fb-b582-4d93-b783-7b333b9fd785)
Still happening in 1.20+
