### ISSUE TITLE
Can not launch server with latest Aviar patch

### ISSUE THREAD

**Issue by MercuryPoisoning** [leafreynolds/cosmere#55]
### Issue description

Server throws various errors when launching with latest Aviar version and fails to boot, client launches fine.

### Steps to reproduce

1. Add latest Aviar version to server mods list along with dependencies.
2. Launch server

### Minecraft version

1.19.2 (Latest)

### Forge version

43.3.0

### Cosmere version

.78

### Other relevant versions

https://discord.com/channels/828383636465123328/837596260168237056/1176609295958278164
Using the version linked here

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/U3n5wv3
https://mclo.gs/Sb1fW55

**Comment by leafreynolds** [comment]
found the problem, thank you, working on a fix.

**Comment by leafreynolds** [comment]
I have confirmed fix in a local server, outside my dev environment this time. New builds processing on curseforge now, keep an eye out for build 79.
