### ISSUE TITLE
[SandMastery] Incorrect number of sand layers received after breaking stack

### ISSUE THREAD

**Issue by leafreynolds** [leafreynolds/cosmere#56]
### Issue description

Breaking taldain layers of sand will only give you a single layer, regardless of how many were stacked.

https://github.com/leafreynolds/cosmere/assets/80794784/10b9b880-8e71-426b-bbf6-68d8944e736c

### Steps to reproduce

1. place a few sand layers
2. break the stack
3. observe number of layers you get back.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.3

### Cosmere version

build 79

**Comment by MoonlitJolteon** [comment]
Fixed in commit 64bdc0f5dd155db371e54f9546de6777ec4230f6
