### ISSUE TITLE
[SandMastery] placing charged taldain sand in pouch disappears, but uncharged works

### ISSUE THREAD

**Issue by leafreynolds** [leafreynolds/cosmere#57]
### Issue description

Title - charged taldain sand disappears when put in sand pouch. 

### Steps to reproduce

1. Start singleplayer
2. place charged sand in pouch
3. observe sand gone
4. place uncharged sand in pouch
5. observe sand appears in output slots

https://github.com/leafreynolds/cosmere/assets/80794784/898d631a-1558-47ee-88e9-bd8aa9e0d78a

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.3

### Cosmere version

build 79

**Comment by MoonlitJolteon** [comment]
fixed in commit e6bcc9980180c0bd71290ab41f7a43a5841b3e95
