### ISSUE TITLE
[Allomancer] Crash when using steel

### ISSUE THREAD

**Issue by MelficeSilesius** [leafreynolds/cosmere#58]
### Issue description

Minecraft crashes because of a ticking entity.
First line of the crashreport reads: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41720_()" because "resultItem" is null

The crashreport is added below.

(Hi. It's Melfice from Discord. Again. 
I'm so, so sorry.)

### Steps to reproduce

1) Have A-Steel
2) Use A-Steel
3) Watch the world freeze
4) Crash to launcher

### Minecraft version

1.19.2 (Latest)

### Forge version

43.3.5

### Cosmere version

CosmereAllomancy-1.19.2-43.1.3-0.5.79.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/kZYDa2b

**Comment by leafreynolds** [comment]
Result item in recipe is somehow null. I suspect there's a malformed recipe in your pack, but don't have any extra information. I've added some guarding to prevent the whitelist crashing for the next build.
