### ISSUE TITLE
Overmastering causes constant posion-like damage.

### ISSUE THREAD

**Issue by AngelOfCreation** [leafreynolds/cosmere#83]
### Issue description

I overmastered using sand launcher for maybe, 30 seconds? My sand powers went away but after that I started taking constant damage every few seconds like I was poisoned. It lasted several hours until eventually I just committed suicide which fixed it.

### Steps to reproduce

1. Overmaster
2. Take damage
3. Die in order to fix it

### Minecraft version

1.19.2 (Latest)

### Forge version

43.3.5

### Cosmere version

0.5.83

### Other relevant versions

Running the server modpack.

**Comment by MoonlitJolteon** [comment]
Working as intended. Overmastery is caused by using up all the water in your body for sand mastery. Due to this you are dehydrated and start taking damage. All you have to do to stop getting hurt is to drink water
